services:
  reporting_service:
    build:
      context: ..
      dockerfile: Dockerfile
      target: production
      args:
        VITE_API_URL: "/api"
    container_name: reporting_service
    expose:
      - "80"
    networks:
      - analysis_network
